# Generated by Django 5.1.2 on 2024-10-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shortener", "0005_alter_kirrurl_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "kirr_url",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shortener.kirrurl",
                    ),
                ),
            ],
        ),
    ]
